// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMozmkG-iqF5BNCojCtLkbZgP3JCd-fg',
    appId: '1:17172294094:web:2ca898993417afb9ffe39f',
    messagingSenderId: '17172294094',
    projectId: 'modern-register',
    authDomain: 'modern-register.firebaseapp.com',
    storageBucket: 'modern-register.firebasestorage.app',
    measurementId: 'G-DLFHDK67R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsdM81uTMeIqfJ3smxCHL1D-4CsLK2cho',
    appId: '1:17172294094:android:5d975811f5784f0dffe39f',
    messagingSenderId: '17172294094',
    projectId: 'modern-register',
    storageBucket: 'modern-register.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXC6RlV39irbXuec6HgqDjpV9zx8_zrk',
    appId: '1:17172294094:ios:d7de264acb14c088ffe39f',
    messagingSenderId: '17172294094',
    projectId: 'modern-register',
    storageBucket: 'modern-register.firebasestorage.app',
    iosBundleId: 'com.example.digitalRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwXC6RlV39irbXuec6HgqDjpV9zx8_zrk',
    appId: '1:17172294094:ios:d7de264acb14c088ffe39f',
    messagingSenderId: '17172294094',
    projectId: 'modern-register',
    storageBucket: 'modern-register.firebasestorage.app',
    iosBundleId: 'com.example.digitalRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYMozmkG-iqF5BNCojCtLkbZgP3JCd-fg',
    appId: '1:17172294094:web:f1e46dd7f57fa5c4ffe39f',
    messagingSenderId: '17172294094',
    projectId: 'modern-register',
    authDomain: 'modern-register.firebaseapp.com',
    storageBucket: 'modern-register.firebasestorage.app',
    measurementId: 'G-ZSEPN1WE22',
  );
}
